#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

#==========================================
# install required applications
# ========================================
echo "Install required files after install"
sudo pacman -S kitty nodejs npm neovim lazygit make
echo "Completed Install"

#==========================================
# Set up Kitty config files
#  ========================================
echo "Setup and Move Kitty Config"
rm -rf $HOME/.config/kitty
#add the new config
ln -s $DOTFILES/kitty $HOME/.config/kitty

#  ========================================
# Set up nvim and create symlink
#  ========================================
echo "Setting Up Lunar Vim config files"
rm -r $HOME/.config/lvim 
#add the new config
ln -s $DOTFILES/lvim $HOME/.config/lvim

echo "Finished"
