#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

#=========================================
# Prop for software install
# #======================================
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update

#==========================================
# install required applications
# ========================================
echo "Install required files after install"
sudo apt-get install kitty nodejs npm neovim ripgrep
echo "Completed Install"

#==========================================
# Set up Kitty config files
#  ========================================
echo "Setup and Move Kitty Config"
rm -rf $HOME/.config/kitty
#add the new config
ln -s $DOTFILES/kitty $HOME/.config/kitty

#  ========================================
# Set up nvim and create symlink
#  ========================================
echo "Setting Up nvim"
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim
rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

echo "Finished"
