#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

#==========================================
# install required applications
# ========================================
echo "Install required files after install"
sudo dnf install kitty nodejs npm neovim make jetbrains-mono-fonts.noarch
sudo dnf copr enable atim/lazygit -y
sudo dnf install lazygit 
echo "Completed Install"

#==========================================
# Set up Kitty config files
#  ========================================
echo "Setup and Move Kitty Config"
rm -rf $HOME/.config/kitty
#add the new config
ln -s $DOTFILES/kitty $HOME/.config/kitty

#  ========================================
# Set up nvim and create symlink
#  ========================================
echo "Setting Up Lunar Vim config files"
rm -r $HOME/.config/lvim 
#add the new config
ln -s $DOTFILES/lvim $HOME/.config/lvim

#  ========================================
# Set up qtile and create symlink
#  ========================================
echo "Setting Up qtile config files"
rm -r $HOME/.config/qtile 
#add the new config
ln -s $DOTFILES/qtile $HOME/.config/qtile
#move the auto start folder
cp $DOTFILES/qtile/autostart.sh /etc/profile.d/
echo "Finished"
